# CICD Using Github Action

name: CI/CD

on:
 push:
  branches:
   - main
# Exclude the workflow to run/update the helm   
  paths-ignore: 
   - 'README.md'
   - 'k8s/**'
   - 'helm/**'

jobs:
  build:
   runs-on: Ubuntu-latest

   steps: 
   - name: Checkout the repository
     uses: action/checkout@v4

   - name: build the go-app 1.22
     uses: action/setup-go@v2
     with:
       go-version: 1.22

   - name: build
     run: go build -o go-web-app 

   - name: test  
     uses: go test ./...

  code-quality:
    runs-on: Ubuntu-latest

    steps:
    - name: checkout repository
      uses: action/checkout@v4

    - name: Run golangci-lint
      uses:  golangci/golangci-lint-action@v6
      with:
        version: v1.56.2 

   push:
      runs-on: Ubuntu-latest

      needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}  

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}   

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "bsutar026@gmail.com"
        git config --global user.name "chagulu01"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push         