# CICD Using Github Action

name: CI/CD

on:
 push:
  branches:
   - main
# Exclude the workflow to run/update the helm   
  paths-ignore: 
   - 'README.md'
   - 'k8s/**'
   - 'helm/**'

jobs:
  build:
   runs-on: Ubuntu-latest

   steps: 
   - name: Checkout the repository
     uses: action/checkout@v4

   - name: build the go-app 1.22
     uses: action/setup-go@v2
     with:
       go-version: 1.22

   - name: build
     run: go build -o go-web-app 

   - name: test  
     uses: go test ./...

  code-quality:
    runs-on: Ubuntu-latest

    steps:
    - name: checkout repository
      uses: action/checkout@v4

    - name: Run golangci-lint
      uses:  golangci/golangci-lint-action@v6
      with:
        version: v1.56.2 

   